from selenium.webdriver.common.by import By


class Locator:
    """Все необходимые селекторы"""
    SEARCH_BAR = (By.XPATH, '//*[@id="stickyHeader"]/div/div[2]/div/div/form/div/div[2]/input')
    SEARCH_RESULTS = (By.XPATH,'//*[@id="paginatorContent"]/div/div/div')
    SEARCH_BUTTON = (By.CSS_SELECTOR,'button[type="submit"]')
    HREF = (By.TAG_NAME,'a')
    NAME = (By.XPATH, "//div/h1")
    ADD_TO_CART1 = (By.XPATH, "//div[text()='В корзину']")
    ADD_TO_CART2 = (By.XPATH, '//*[@id="layoutPage"]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/button/div[2]')
    PICTURES = (By.XPATH, '//*[@id="layoutPage"]/div/div/div/div/div/div/div/div/div/div/div/div[1]/div[1]/div[1]/div[1]/div[1]/div/div/div')
    CART = (By.XPATH, '//*[@id="stickyHeader"]/div/div[3]/a[2]')
    CHECKBOX_IN_CART = (By.XPATH, '//*[@id="layoutPage"]//div//label')
    GO_TO_PAY = (By.XPATH, '//*[@id="layoutPage"]/div[1]/div/div/div[2]/div[4]/div[2]/div/section/div[1]/div[1]/button')
    AUTH = (By.XPATH, "//div[@data-widget='profileMenuAnonymous']")
    AUTH_IFRAME = (By.XPATH, '//*[@id="authFrame"]')
    ADRESS_MAIN = (By.XPATH, "//div[contains(text(), 'Уточнить адрес')]")
    ADRESS_CHOOSE = (By.XPATH, "//span[contains(text(), 'Выбрать на карте')]")
    NUMBER_FIELD = (By.XPATH, '//*[@id="layoutPage"]/div[1]/div/div/div[4]/div/div/div[1]/label/div/div')
    BUTTON_AUTH = (By.XPATH, '//*[@id="layoutPage"]/div[1]/div/div/div[5]/button')
    CODE_FIELD = (By.XPATH, '//*[@id="layoutPage"]/div[1]/div/div/div[5]/div[1]/label')
    CODE_FIELD_2 = (By.CSS_SELECTOR, "input[name='otp']")
    CODE_BANNED = (By.XPATH, '//*[@id="layoutPage"]/div[1]/div/div/div[4]/div/div/div[1]/div')
    GET_NEW_CODE = (By.XPATH, '//*[@id="layoutPage"]/div[1]/div/div/div[5]/div[2]/div/a')
    CODE_TYPE = (By.XPATH, '//*[@id="layoutPage"]/div[1]/div/div/div[2]/span')
    IF_EMAIL = (By.XPATH, '//*[@id="layoutPage"]/div[1]/div/div/div[3]/span')
    CONFIRM_EULA = (By.XPATH, '//*[@id="layoutPage"]/div[1]/div/div/div[4]/div[3]/label')
    ADD_ADRESS = (By.XPATH, "//p[contains(@class, 'cd_7') and contains(text(), 'Добавить')]")
    ADRESS = (By.XPATH, '//div/textarea')
    ADRESS_CONFIRM_SAMOVIVOZ = (By.XPATH, "//div[text()='Заберу отсюда']")
    ADRESS_CONFIRM1 = (By.XPATH, "//div[text()='Продолжить']")
    ADRESS_CONFIRM2 = (By.XPATH, "//div[text()='Сохранить адрес']")
    ADRESS_CLEAR = (By.XPATH, '//*[@id="layoutPage"]/div/div/div/div/div/div/div/div/div/div/form/div/div/fieldset/div/div/div/div/label/div/div/div/div/button')
    FAST_PAY = (By.XPATH, "//div[contains(@style, 'fast_pay')]")
    NEXT_PAY = (By.XPATH, '//*[@id="payment-info"]/div/div/div/div/div[2]/button/span')
    PAY = (By.XPATH, "//div[text()='Оплатить онлайн']")
    PROMO_BUTTON = (By.XPATH, '//*[@id="layoutPage"]/div/div/div/div/div/div/div/div/div/div/div/div/p')
    PROMO_FIELD = (By.XPATH, '//div/input')
    PROMO_CONFIRM = (By.XPATH, '//*[@id="layoutPage"]/div/div/div/div/div/div/div/div/div/div/div/form/div/button/div[2]')
    COURIER = (By.XPATH, "//span[text()='Курьером']")
    MINUS_ZOOM = (By.XPATH, '//*[@id="sdk-map-container"]/div/div/div[2]/div/div/div/div[2]')
    FLAT = (By.XPATH, "//p[contains(text(), 'Квартира')]")
    ENTRANCE = (By.XPATH, "//p[contains(text(), 'Подъезд')]")
    FLOOR = (By.XPATH, "//p[contains(text(), 'Этаж')]")
    DOORPHONE = (By.XPATH, "//p[contains(text(), 'Домофон')]")
    COMMENT_COURIER = (By.XPATH, "//p[contains(text(), 'Комментарий курьеру')]")
    ORDER_FIO = (By.XPATH, "//p[contains(text(), 'Имя и фамилия')]")
    ORDER_NUMBER = (By.XPATH, "//p[contains(text(), 'Телефон')]")
    QR_CODE = (By.XPATH, "//img[@alt='QR-код']")